import Document, { Head, Html, Main, NextScript } from 'next/document'
import { ReactElement } from 'react'
import i18nextConfig from '../../next-i18next.config'

export default class MyDocument extends Document {
  // static async getInitialProps(ctx: DocumentContext): Promise<DocumentInitialProps> {
  // }

  render(): ReactElement {
    const currentLocale =
      this.props.__NEXT_DATA__.locale ?? i18nextConfig.i18n.defaultLocale
    return (
      <Html lang={currentLocale}>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <meta charSet='utf-8' />
          <meta name='theme-color' content='#000000' />
          <link rel='icon' href='/favicon.ico' />
          <link
            rel='apple-touch-icon'
            sizes='76x76'
            href='/img/brand/apple-icon.png'
          />
        </Head>
        <body className='text-slate-900 antialiased'>
          <div id='page-transition'></div>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
